- name: Install brew packages
  homebrew: name={{ item }}
  with_items:
    - ansible
    - ansible-lint
    - bat
    - brotli
    - gettext
    - git
    - go
    - htop
    - syncthing
    - tmux
    - topgrade

- name: Install brew cask packages
  homebrew_cask: name={{ item }}
  with_items:
    - authy
    - cyberduck
    - dash
    - dropbox
    - iterm2
