- name: Install base packages
  homebrew: name={{ item }}
  with_items:
    - ansible
    - bat
    - brotli
    - gettext
    - git
    - htop
    - mas
    - syncthing
    - tmux
    - topgrade

- name: Install base cask packages
  homebrew_cask: name={{ item }}
  with_items:
    - cyberduck
    - dropbox
    - enpass
    - evernote
